### ISSUE TITLE
Code is different to the tutorial

### ISSUE THREAD

**Issue by RachBLondon** [eguneys/react-redux-todo-app#1]
Hi,

I have been working through the sitepoint tutorial but have found the code different on here. Also wondering why all the react code is in HelloApp?

**Comment by eguneys** [comment]
Thanks for your interest.

The tutorial shows the overall structure of a redux app. It focuses on redux and testing, and how to connect with react. It skips most of react code and is simplified for brevity.
I've used this seed project https://github.com/eguneys/react-seed. Just didn't rename the folder.
